Merged in DEVOPS-140-ci-cd-setup-topps-staging (pull request #61)
jenkins/order-gateway-cd/staging/Jenkinsfile edited online with Bitbucket

* jenkins/order-gateway-cd/staging/Jenkinsfile edited online with Bitbucket

diff --git a/jenkins/order-gateway-cd/staging/Jenkinsfile b/jenkins/order-gateway-cd/staging/Jenkinsfile
--- a/jenkins/order-gateway-cd/staging/Jenkinsfile
+++ b/jenkins/order-gateway-cd/staging/Jenkinsfile
@@ -23,7 +23,11 @@ pipeline {
         ACR_VPC_REGISTRY = 'prod-plugin-acr-registry-vpc.cn-guangzhou.cr.aliyuncs.com'
         ACR_NAMESPACE    = 'production'
         ACR_REPO         = 'order-gateway'
-        DEPLOYMENT_FILE  = 'topps/order-gateway/staging/deployment.yml'
+
+        DEPLOYMENT_FILE1 = 'topps/order-gateway/staging/deployment.yml'
+
+        DEPLOYMENT_FILE2 = 'topps/order-gateway-worker/staging/deployment.yml'
+        DEPLOYMENT_FILE3 = 'topps/order-gateway-beat/staging/deployment.yml'
         
     }
 
@@ -71,20 +75,50 @@ pipeline {
             steps {
                 dir('gitops-ack') {
                     sh """
-                        if ! grep -q '${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:' ${env.DEPLOYMENT_FILE}; then
-                            echo "ERROR: Expected image pattern not found in ${env.DEPLOYMENT_FILE}"
+                        echo "update DEPLOYMENT_FILE1"
+                        if ! grep -q '${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:' ${env.DEPLOYMENT_FILE1}; then
+                            echo "ERROR: Expected image pattern not found in ${env.DEPLOYMENT_FILE1}"
                             exit 1
                         fi
 
-                        sed -i 's|\\(image:[[:space:]]*${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:\\)[^[:space:]]*|\\1${env.IMAGE_TAG}|g' ${env.DEPLOYMENT_FILE}
+                        sed -i 's|\\(image:[[:space:]]*${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:\\)[^[:space:]]*|\\1${env.IMAGE_TAG}|g' ${env.DEPLOYMENT_FILE1}
                         
-                        if ! grep -q '${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:${env.IMAGE_TAG}' ${env.DEPLOYMENT_FILE}; then
-                            echo "ERROR: Image tag replacement failed! Please check ${env.DEPLOYMENT_FILE}"
+                        if ! grep -q '${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:${env.IMAGE_TAG}' ${env.DEPLOYMENT_FILE1}; then
+                            echo "ERROR: Image tag replacement failed! Please check ${env.DEPLOYMENT_FILE1}"
                             exit 1
                         fi
+                        
+                        echo "update DEPLOYMENT_FILE2"
+                        if ! grep -q '${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:' ${env.DEPLOYMENT_FILE2}; then
+                            echo "ERROR: Expected image pattern not found in ${env.DEPLOYMENT_FILE2}"
+                            exit 1
+                        fi
+
+                        sed -i 's|\\(image:[[:space:]]*${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:\\)[^[:space:]]*|\\1${env.IMAGE_TAG}|g' ${env.DEPLOYMENT_FILE2}
+                        
+                        if ! grep -q '${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:${env.IMAGE_TAG}' ${env.DEPLOYMENT_FILE2}; then
+                            echo "ERROR: Image tag replacement failed! Please check ${env.DEPLOYMENT_FILE2}"
+                            exit 1
+                        fi                        
+
+                        echo "update DEPLOYMENT_FILE3"
+                        if ! grep -q '${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:' ${env.DEPLOYMENT_FILE3}; then
+                            echo "ERROR: Expected image pattern not found in ${env.DEPLOYMENT_FILE3}"
+                            exit 1
+                        fi
+
+                        sed -i 's|\\(image:[[:space:]]*${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:\\)[^[:space:]]*|\\1${env.IMAGE_TAG}|g' ${env.DEPLOYMENT_FILE3}
+                        
+                        if ! grep -q '${env.ACR_VPC_REGISTRY}/${env.ACR_NAMESPACE}/${env.ACR_REPO}:${env.IMAGE_TAG}' ${env.DEPLOYMENT_FILE3}; then
+                            echo "ERROR: Image tag replacement failed! Please check ${env.DEPLOYMENT_FILE3}"
+                            exit 1
+                        fi
+                        
 
                         echo "Verified: image tag updated successfully"
-                        grep 'image:' ${env.DEPLOYMENT_FILE}
+                        grep 'image:' ${env.DEPLOYMENT_FILE1}
+                        grep 'image:' ${env.DEPLOYMENT_FILE2}
+                        grep 'image:' ${env.DEPLOYMENT_FILE3}
                     """
                 }
             }
